=== GovernorTrout/WSD-project/web/WEB-INF/Tutors.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.uts.edu.au/31284/wsdtutor"
 xmlns="http://www.uts.edu.au/31284/wsdtutor"
 elementFormDefault="qualified">
 
<xs:simpleType name="name">
    <xs:restriction base ="xs:string">
        <xs:pattern value ="([A-Z][a-z]+\s)*([A-Z][a-z]+\s*)"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="email">
    <xs:restriction base ="xs:string">
        <xs:pattern value ="\S+@\S+"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="dob">
    <xs:restriction base ="xs:string">
        <xs:pattern value ="\d{2}\-\d{2}\-\d{4}"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="password">
    <xs:restriction base ="xs:string">
        <xs:pattern value ="\w+\S"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="type">
    <xs:restriction base ="xs:string">
        <xs:pattern value ="Tutor"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="subject">
    <xs:restriction base ="xs:string">
        <xs:pattern value ="WSD|USP|SEP|AppProg|MobileApp"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="availability">
    <xs:restriction base ="xs:string">
        <xs:pattern value ="Available|Unavailable"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name = "tutors" >
    <xs:complexType>
        <xs:sequence>
            <xs:element name ="tutor" maxOccurs ="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name = "name" type= "name"/>
                        <xs:element name = "email" type= "email"/>
                        <xs:element name = "password" type = "password"/>
                        <xs:element name = "type" type = "type"/>                         
                        <xs:element name = "dob" type = "dob"/> 
                        <xs:element name = "subject" type = "subject"/>
                        <xs:element name = "availability" type ="availability"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>           
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== GovernorTrout/WSD-project/web/WEB-INF/tutors.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="tutors.xsl"?>
<tutors xmlns="http://www.uts.edu.au/31284/wsdtutor"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.uts.edu.au/31284/wsdtutor Tutors.xsd">
    <tutor>
        <name>Test Tutor</name>
        <email>tutor@tutoring.com</email>
        <password>testpassword</password>
        <type>Tutor</type>
        <dob>11-02-1984</dob>
        <subject>SEP</subject>    
        <availability>Available</availability>
    </tutor>
</tutors>
